# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'r:\EXIF_CRC32Reader\UIMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(267, 112)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/icon-bookmark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.btnExifGen = QtWidgets.QPushButton(Form)
        self.btnExifGen.setGeometry(QtCore.QRect(35, 15, 201, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btnExifGen.setFont(font)
        self.btnExifGen.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/icon-settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExifGen.setIcon(icon1)
        self.btnExifGen.setIconSize(QtCore.QSize(24, 24))
        self.btnExifGen.setObjectName("btnExifGen")
        self.btnExifQuery = QtWidgets.QPushButton(Form)
        self.btnExifQuery.setGeometry(QtCore.QRect(35, 55, 201, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btnExifQuery.setFont(font)
        self.btnExifQuery.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/icon-clipboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExifQuery.setIcon(icon2)
        self.btnExifQuery.setIconSize(QtCore.QSize(24, 24))
        self.btnExifQuery.setObjectName("btnExifQuery")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Main"))
        self.btnExifGen.setText(_translate("Form", "Generate EXIF Info"))
        self.btnExifQuery.setText(_translate("Form", "Query Exif Info"))
import resources_rc
